FROM intel/oneapi-basekit:latest 
COPY mklMultiplication.cpp /usr/share/mkl/mklMultiplication.cpp
WORKDIR /usr/share/mkl  
RUN clang++ -o mklmul mklMultiplication.cpp -I${MKLROOT}/include -L${MKLROOT}/lib/intel64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl
ENTRYPOINT ["./mklmul"]
