FROM intel/oneapi-basekit:latest 
COPY mklCho_paralel.cpp /usr/share/mkl/mklCho_paralel.cpp
WORKDIR /usr/share/mkl  
#RUN clang++ -o mklcho mklCho.cpp -I${MKLROOT}/include -L${MKLROOT}/lib/intel64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl
#RUN clang++ -o mklcho mklCho.cpp -I${MKLROOT}/include -L${MKLROOT}/lib/intel64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl
RUN icpx -o mklchopa mklCho_paralel.cpp -I${MKLROOT}/include -L${MKLROOT}/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_intel_thread -lpthread -lm -ldl -fopenmp
ENTRYPOINT ["./mklchopa"]
