FROM gcc:latest
RUN apt-get update && apt-get upgrade && apt-get install sudo && apt-get install nano \ 
    libeigen3-dev
COPY eiSVD.cpp /usr/share/myapp/eiSVD.cpp 
WORKDIR /usr/share/myapp
RUN g++ -I /usr/include/eigen3/ eiSVD.cpp -o eiSVD
ENTRYPOINT ["./eiSVD"]
