FROM gcc:latest   
RUN apt-get update && apt-get install -y \
        make \
        cmake \  
        git \  
        libopenblas-dev \ 
        liblapack-dev \
        liblapacke-dev \
        && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/share/lapack  
COPY lanoCholesky.cpp /usr/share/lapack/lanoCholesky.cpp
RUN g++ -o lanocho lanoCholesky.cpp -lopenblas -llapacke -lm -lpthread
ENTRYPOINT ["./lanocho"] 
