FROM gcc:latest   
RUN apt-get update && apt-get install -y \
        make \
        cmake \  
        git \  
        libopenblas-dev \ 
        liblapack-dev \
        liblapacke-dev \
        && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/share/lapack  
COPY laLU.cpp /usr/share/lapack/laLU.cpp
RUN g++ -o laLU laLU.cpp -lopenblas -llapacke -lm -lpthread
ENTRYPOINT ["./laLU"] 
