FROM gcc:latest   
RUN apt-get update && apt-get install -y \
        make \
        cmake \  
        git \  
        libopenblas-dev \ 
        liblapack-dev \
        liblapacke-dev \
        && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/share/lapack  
COPY laCholez.cpp /usr/share/lapack/laholez.cpp
RUN g++ -o laCholez laCholez.cpp -lopenblas -llapacke -lm -lpthread
ENTRYPOINT ["./laCholez"] 
