FROM intel/oneapi-basekit:latest 
COPY mkl.cpp /usr/share/mkl/mkl.cpp
WORKDIR /usr/share/mkl  
RUN clang++ -o mkl mkl.cpp -I${MKLROOT}/include -L${MKLROOT}/lib/intel64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl
ENTRYPOINT ["./mkl"]
